### PR TITLE
Creating a webinar throws an "object cannot be instantiated" error.

### PR DESCRIPTION
**Pull request by michael-aj-kennedy**
Could not create an instance of type ZoomNet.Models.Webinar. Type is an interface or abstract class and cannot be instantiated.

See issue #76

### CODE REVIEW

**Comment by Jericho** [comment]
I suspect your may not have been fully up-to-date when you submitted this PR because this was resolved yesterday in issue #75 and PR #74

**Comment by michael-aj-kennedy** [comment]
haha, no problem - looks like the counterpart PR was submitted between me spotting the issue & having the time to do something about it ;)

**Comment by Jericho** [comment]
Perfect. If you don't mind, I'll close this PR and the associated issue, but know that I really appreciate you taking the time to investigate this problem and submit a PR to solve it.

**Comment by michael-aj-kennedy** [comment]
No problem, thanks

**Pull request closed without merging**
